### ISSUE TITLE
Michigan

### ISSUE THREAD

**Issue by kofron** [deanputney/earlyvoting#46]
* NA and NaN values in the header
* bold text for "Absentee ballot application"
* "Warning" seems a bit strong for the last bullet point in the info section

**Comment by deanputney** [comment]
This NA and NaN issue is caused by the `N/A` value in the `year-2020-early-voting-starts` and `year-2020-early-voting-ends` columns in our `early-voting-data` tab. 

Unfortunately this means we need to do another `-manual` and `-combined` column. I would very much like to rearrange the columns in this sheet in order to do that, and while I think that's OK I'm not entirely sure.

I think I'm just gonna go for it and pay the price later if that messes things up. If it breaks anything, it'll break the ingestion and not the display, which gives us some time to course correct if needed.

**Comment by kofron** [comment]
Also, the "michigan election website" button goes nowhere.
