### ISSUE TITLE
Utah

### ISSUE THREAD

**Issue by kofron** [deanputney/earlyvoting#69]
VBM formatting just a little odd, some bulleted and some not

**Comment by deanputney** [comment]
I'm kinda not sure what this `early-voting-by-mail-info` field is meant to do, especially since it's pulling from `early-voting-notes-combined`... Sounds like this might be a field we want to separate out or exclude?

I see that it's repetitive here, but I don't think it warrants changing the sheet unless we're going to create more clarity around why this field exists and is different from `early-voting-notes-combined`.
